#ifndef CLCD_CONFIG_H_
#define CLCD_CONFIG_H_

#define CLCD_DATA_PORT MDIO_PORTA
#define CLCD_CTRL_PORT MDIO_PORTC
#define CLCD_RS_PIN MDIO_PIN0
#define CLCD_RW_PIN MDIO_PIN1
#define CLCD_E_PIN MDIO_PIN2

#endif
