#ifndef TIMER_CONFIG_H_
#define TIMER_CONFIG_H_

#define WAVEFORM_MODE	WGM_TIMER_COUNTER_MODE_FAST_PWM
#define WGM_TIMER_COUNTER_MODE_NORMAL 0x00
#define WGM_TIMER_COUNTER_MODE_PWM 0x01
#define WGM_TIMER_COUNTER_MODE_CTC 0x10
#define WGM_TIMER_COUNTER_MODE_FAST_PWM 0x011

/* compare match output mode*/
#define COM_TYPE	FAST_PWM_CLEAR_ON_COM
#define COM_NORMAL 0x00
#define COM_TOGGLE 0x01
#define COM_CLEAR 0x10
#define COM_SET 0x11

#define FAST_PWM_NORMAL 0x04
#define FAST_PWM_RESERVED 0x05
#define FAST_PWM_CLEAR_ON_COM 0X06
#define FAST_PWM_SET_ON_COM 0X07

#define PHASE_CORRECT_PWM_NORMAL 0x08
#define PHASE_CORRECT_PWM_RESERVED 0x09
#define PHASE_CORRECT_PWM_CLEAR_ON_COM 0X10
#define PHASE_CORRECT_PWM_SET_ON_COM 0x11

#define CLOCK_SOURCE_PRESCALER	PRESCALING_BY_8
#define TIMER1_CLOCK_SOURCE_PRESCALER	PRESCALING_BY_8

#define NO_CLOCK_SOURCE 0X0
#define NO_PRESCALING 0X1
#define PRESCALING_BY_8 0X2
#define PRESCALING_BY_64 0X3
#define PRESCALING_BY_256 0X4
#define PRESCALING_BY_1024 0X5
#define PRESCALING_EXT_ON_FALLING 0x6
#define PRESCALING_EXT_ON_RISING 0x7

#define OCIE_STATUS		OCIE_DIS
#define OCIE_EN 0x1
#define OCIE_DIS 0x2
#define TOIE_STATUS		TOIE_DIS
#define TOIE_EN 0x3
#define TOIE_DIS 0x4


/* TIMER1 COMPARE OUTPUT MODE */
#define TIMER1_COMPARE_OUTPUT_MODE_A 				NORMAL_OPERATION
#define TIMER1_COMPARE_OUTPUT_MODE_B 				NORMAL_OPERATION

/* Select the  Input Capture Edge Select */
#define INPUT_CAPTURE_EDGE_SELECT					ICU_RISING_EDGE
#define	ICU_RISING_EDGE								0x1
#define ICU_FALLING_EDGE							0x2

#define NORMAL_OPERATION 							1
#define TOGGLE_ON_COMPARE 							2
#define CLEAR_ON_COMPARE_NO_PWM 					3
#define SET_ON_COMPARE_NO_PWM 						4
#define TOGGLE_ON_COMPARE 							5
#define CLEAR_ON_COMPARE_SET_ON_TOP 				6
#define SET_ON_COMPARE_CLEAR_ON_TOP 				7
#define CLEAR_ON_COMPARE_UP_SET_ON_COM_DOWN 		8
#define SET_ON_COMPARE_UP_CLEAR_ON_COM_DOWN 		9

/* TIMER1 WAVEFORM MODE */
#define TIMER1_WAVEFORM_GEN_MODE 		NORMAL_OPERATION
#define PWM_PHASECOR_8BITS 				2
#define PWM_PHASECOR_9BITS 				3
#define PWM_PHASECOR_10BITS 			4
#define CTC								5
#define FAST_PWM_8BITS					6
#define FAST_PWM_9BITS					7
#define FAST_PWM_10BITS 				8
#define PWM_PHASE_FREQ_COR_ICR1 		9
#define PWM_PHASE_FREQ_COR_OCR1A 		10
#define PWM_PHASE_COR_ICR1				11
#define PWM_PHASE_COR_OCR1A				12
#define CTC_ICR1						13
#define FAST_PWM_ICR1					14
#define FAST_PWM_OCR1A					15

/* TICIE1: Timer/Counter1, Input Capture Interrupt Enable */
#define TICIE1_STATUS					TICIE1_ENABLE
#define TICIE1_ENABLE					1
#define TICIE1_DISABLE					2

/* OCIE1A: Timer/Counter1, Output Compare A Match Interrupt Enable */
#define OCIE1A_STATUS					OC1E1A_DISABLE
#define OCIE1A_ENABLE					1
#define OCIE1A_DISABLE					2

/* Timer/Counter1, Output Compare B Match Interrupt Enable */
#define OCIE1B_STATUS					OCIE1B_DISABLE
#define OCIE1B_ENABLE					1
#define OCIE1B_DISABLE					2

/*  TOIE1: Timer/Counter1, Overflow Interrupt Enable */
#define TOIE1_STATUS					TOIE1_DISABLE
#define TOIE1_ENABLE					1
#define TOIE1_DISABLE					2

/* Select the Input capture noise option */
#define INPUT_CAPTURE_NOISE_CANCELER_STATUS		INPUT_CAPTURE_NOISE_CANCELER_DISABLE
#define INPUT_CAPTURE_NOISE_CANCELER_ENABLE 	1
#define INPUT_CAPTURE_NOISE_CANCELER_DISABLE	2


#endif