#ifndef PORT_PRIVATE_H_
#define PORT_PRIVATE_H_

#define CONC(b7,b6,b5,b4,b3,b2,b1,b0)             CONC_HELPER(b7,b6,b5,b4,b3,b2,b1,b0)
#define CONC_HELPER(b7,b6,b5,b4,b3,b2,b1,b0)      0b##b7##b6##b5##b4##b3##b2##b1##b0

#define PORTA_DIR                                 CONC(PORTA_PIN7_DIR,PORTA_PIN6_DIR,PORTA_PIN5_DIR,PORTA_PIN4_DIR,PORTA_PIN3_DIR,PORTA_PIN2_DIR,PORTA_PIN1_DIR,PORTA_PIN0_DIR) 
#define PORTB_DIR                                 CONC(PORTB_PIN7_DIR,PORTB_PIN6_DIR,PORTB_PIN5_DIR,PORTB_PIN4_DIR,PORTB_PIN3_DIR,PORTB_PIN2_DIR,PORTB_PIN1_DIR,PORTB_PIN0_DIR) 
#define PORTC_DIR                                 CONC(PORTC_PIN7_DIR,PORTC_PIN6_DIR,PORTC_PIN5_DIR,PORTC_PIN4_DIR,PORTC_PIN3_DIR,PORTC_PIN2_DIR,PORTC_PIN1_DIR,PORTC_PIN0_DIR) 
#define PORTD_DIR                                 CONC(PORTD_PIN7_DIR,PORTD_PIN6_DIR,PORTD_PIN5_DIR,PORTD_PIN4_DIR,PORTD_PIN3_DIR,PORTD_PIN2_DIR,PORTD_PIN1_DIR,PORTD_PIN0_DIR) 

#define PORTA_INITVALUE                            CONC(PORTA_PIN7_INITVALUE,PORTA_PIN6_INITVALUE,PORTA_PIN5_INITVALUE,PORTA_PIN4_INITVALUE,PORTA_PIN3_INITVALUE,PORTA_PIN2_INITVALUE,PORTA_PIN1_INITVALUE,PORTA_PIN0_INITVALUE) 
#define PORTB_INITVALUE                            CONC(PORTB_PIN7_INITVALUE,PORTB_PIN6_INITVALUE,PORTB_PIN5_INITVALUE,PORTB_PIN4_INITVALUE,PORTB_PIN3_INITVALUE,PORTB_PIN2_INITVALUE,PORTB_PIN1_INITVALUE,PORTB_PIN0_INITVALUE) 
#define PORTC_INITVALUE                            CONC(PORTC_PIN7_INITVALUE,PORTC_PIN6_INITVALUE,PORTC_PIN5_INITVALUE,PORTC_PIN4_INITVALUE,PORTC_PIN3_INITVALUE,PORTC_PIN2_INITVALUE,PORTC_PIN1_INITVALUE,PORTC_PIN0_INITVALUE) 
#define PORTD_INITVALUE                            CONC(PORTD_PIN7_INITVALUE,PORTD_PIN6_INITVALUE,PORTD_PIN5_INITVALUE,PORTD_PIN4_INITVALUE,PORTD_PIN3_INITVALUE,PORTD_PIN2_INITVALUE,PORTD_PIN1_INITVALUE,PORTD_PIN0_INITVALUE) 


#endif